# Generated by Django 6.0.1 on 2026-01-23 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_project_created_at_project_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_approved',
        ),
    ]
