# Generated by Django 6.0.1 on 2026-02-02 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphase',
            name='progress',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
