# Generated by Django 6.0.1 on 2026-01-19 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_date', models.DateField(auto_now_add=True)),
                ('mode', models.CharField(max_length=50)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contractors.invoice')),
            ],
        ),
    ]
