# Generated by Django 6.0.1 on 2026-02-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='initial_stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='stock',
            field=models.FloatField(default=0),
        ),
    ]
