# Generated by Django 6.0.1 on 2026-02-03 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_alter_projectphase_progress'),
        ('materials', '0002_material_initial_stock_alter_material_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialusage',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_logs', to='construction.projectphase'),
        ),
    ]
