# Generated by Django 6.0.1 on 2026-02-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_issue'),
        ('contractors', '0002_alter_contractor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='company_name',
        ),
        migrations.AddField(
            model_name='contractor',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='contractors', to='construction.project'),
        ),
    ]
