# Generated by Django 6.0.1 on 2026-02-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0004_projectcontractor_alter_invoice_contractor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
