# Generated by Django 6.0.1 on 2026-02-03 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_alter_projectphase_progress'),
        ('contractors', '0005_invoice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='construction.projectphase'),
        ),
    ]
