# Generated by Django 6.0.1 on 2026-02-04 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_alter_projectphase_progress'),
        ('labour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='construction.projectphase'),
        ),
    ]
